name: build
on:
  pull_request:
  push:
    tags:
      - "*"
      - "!v*"
  release:
    types:
      - published
jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 23.2.7.2-emqx-2
          - 24.0.5-emqx-1
        os:
          - ubuntu20.04
          - ubuntu18.04
          - ubuntu16.04
          - debian10
          - debian9
          - centos8
          - centos7
    container:
        image: ghcr.io/emqx/emqx-builder-helper/5.0:${{ matrix.otp }}-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - shell: bash
        run: make
      - if: failure()
        run: cat rebar3.crashdump
      - run: ./_build/emqtt_bench/rel/emqtt_bench/bin/emqtt_bench

  docker:
    name: docker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 23.2.7.2-emqx-2
          - 24.0.5-emqx-1
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/emqtt-bench
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/build-push-action@v2
        if: github.event_name != 'release'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            FROM=ghcr.io/emqx/emqx-builder-helper/5.0:${{ matrix.otp }}-alpine3.14
      - uses: docker/build-push-action@v2
        if: github.event_name == 'release'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            FROM=ghcr.io/emqx/emqx-builder-helper/5.0:${{ matrix.otp }}-alpine3.14
